### ISSUE TITLE
Is this a working library/module?

### ISSUE THREAD

**Issue by kdschlosser** [adafruit/Adafruit_CircuitPython_MCP2515#2]
as the issue topic asks.. is it?

**Comment by ladyada** [comment]
have you tried it?

**Comment by kdschlosser** [comment]
I have not but from looking at all of the todo notes in the code and also some pretty recent commit names It suggests it is not a finished product.

**Comment by ladyada** [comment]
ok please try it and open up issues relating to bugs or missing functionality :)
