### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by guilherme-daros** [adafruit/Adafruit_CircuitPython_MCP2515#6]
Every time I try importing this module into my python code the interpreter raises this ModuleNotFoundError exception. I checked and the package is in the `.env/lib/python3.7/site-packages` folder.

My hardware is a Raspberry Pi Zero W

Any sugestions?

```shell
Python 3.7.3 (default, Jul 25 2020, 13:03:44)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import adafruit_mcp2515
Traceback (most recent call last):
  File "<stdin>", line 1 in <module>
ModuleNotFoundError: No module named 'adafruit_mcp2515'
>>>
```

**Comment by dherrada** [comment]
Pretty sure I've found the issue. Gonna release and then test it

**Comment by dherrada** [comment]
@ladyada So it sees it now that I changed it to packages instead of py_modules, but it gets hung up on line 31 when it tries to import .canio. I think that if I add adafruit_mcp2515.canio to packages that might fix it, but I wanted to see if you knew if that is the right thing to do first.

**Comment by ladyada** [comment]
ahh i have no idea - i think try the BLE thingy? let me know if that works :D

**Comment by dherrada** [comment]
Ok. I'll give it a go

**Comment by dherrada** [comment]
@ladyada So that didn't work. It's technically less broken than it was before but it still doesn't import right. I'll try one other thing but after that, I'm pretty out of ideas.

**Comment by dherrada** [comment]
@guilherme-daros Hey could you try reinstalling it (with either -U or --force-reinstall) and let me know if you can import it. I got it working and tested on a Pi 4 but the issue had to do with setup.py so it should hopefully work on your Zero W. Thanks!

**Comment by guilherme-daros** [comment]
it works!! thank you so much

**Comment by dherrada** [comment]
No problem. Glad it works!
